# action.yml
name: 'Tag/Release on Push Action'
description: 'Creates a Tag/Release on pushes to a branch'
author: 'rymndhng'
inputs:
  bump_version_scheme:
    description: 'The bumping scheme to use by default. One of minor|major|patch|norelease'
    required: true
outputs:
  release_on_push_action_tag:
    description: 'Tag of released version.'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'award'
  color: 'blue'
